stages:
    - mirror
    - publish

mirror:
    stage: mirror
    image: node:latest
    script:
        #github
        - USERNAME=pektin-dolly
        - git config --global user.email "runner@${CI_SERVER_HOST}"
        - git config --global user.name "runner"
        - git fetch --unshallow origin || true
        - git remote remove origin
        - git remote add origin https://${USERNAME}:${GITHUB_TOKEN}@github.com/pektin-dns/${CI_PROJECT_NAME}.git
        - git push --set-upstream origin HEAD:refs/heads/main -f || true
        #gitlab
        - git remote remove origin
        - git remote add origin https://${USERNAME}:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
        - git push --set-upstream origin HEAD:refs/heads/main -f

publish:
    stage: publish
    image: pektin/rust-wasm-builder
    script:
        #publish to npm
        - ls -l
        - wasm-pack build
        - wasm-opt -Oz -o pkg/wasm_dns_bg.wasm pkg/wasm_dns_bg.wasm
        - du -hs pkg/
        - cd pkg
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish --verbose --access public
