image: alpine

stages:
    - publish

publish:
    stage: publish
    image: pektin/rust-wasm-builder
    script:
        #publish to npm
        - sh build.sh
        - "cd dist/bundler/"
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish --verbose --access public
        - "cd -"
        - "cd dist/web/"
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish --verbose --access public
        - "cd -"
        - "cd dist/nodejs/"
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish --verbose --access public
        - "cd -"
