include:
    - project: pektin/pektin-dist
      ref: main
      file:
          - scripts/mirror.yml

image: alpine

stages:
    - mirror
    - publish

publish:
    stage: publish
    image: pektin/rust-wasm-builder
    script:
        #publish to npm
        - wasm-pack build
        - wasm-opt -Oz -o pkg/toluol_wasm_bg.wasm pkg/toluol_wasm_bg.wasm
        - du -hs pkg/
        - cd pkg
        - sed -i "s|toluol-wasm|@pektin/toluol-wasm|g" package.json
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish --verbose --access public
